### ISSUE TITLE
Code sample throws TypeError

### ISSUE THREAD

**Issue by john-patterson** [tritium21/node-irc-dcc#19]
In this block of code

```    
dcc.acceptChat(args.host, args.port, (chat) => {
    chat.on("line", (line) => {
        chat.say("You said: " + line);
    });
});
```

I get the following exception:

```     
chat.on("line", (line) => {
        ^

TypeError: Cannot read property 'on' of null
    at dcc.acceptChat (/home/johnp/Projects/javascript/node-irc-dcc/examples/bookz.js:14:9)
    at Socket.con.on (/home/johnp/Projects/javascript/node-irc-dcc/lib/dcc.js:175:9)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:188:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:10)
```

Looking into the code I saw that in the definition of `acceptChat` we have the following code:
```
    con.on("connect", () => {
        callback(null, new Chat(con));
    });
```
Which passes `null` as the first argument. Changing the sample code to 
```    
dcc.acceptChat(args.host, args.port, (_, chat) => {
    chat.on("line", (line) => {
        chat.say("You said: " + line);
    });
});
```

Seems to work as desired. I'm pretty new to node and JS, so I don't know if there's something I'm missing.

**Comment by john-patterson** [comment]
From this https://stackoverflow.com/questions/22518978/nodejs-callback-with-null-as-first-argument this might have been meant to be a space to pipe errors into the callback. If so, the code sample still needs updating.

**Comment by john-patterson** [comment]
Updated docs in this commit:
https://github.com/john-patterson/node-irc-dcc/commit/ce79d55c3a48c4a12bc3b706338a47cb249969dd

**Comment by tritium21** [comment]
What version of node are you using?

**Comment by tritium21** [comment]
Readme isn't documentation.
http://node-irc-dcc.readthedocs.io/

**Comment by john-patterson** [comment]
Version 7.10.0. And okay, sure.
